// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// message 对应生成代码的 struct
// 定义客户端请求的数据格式
type UserReq struct {
	// [修饰符] 类型 字段名 = 标识符;
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReq) Reset()         { *m = UserReq{} }
func (m *UserReq) String() string { return proto.CompactTextString(m) }
func (*UserReq) ProtoMessage()    {}
func (*UserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReq.Unmarshal(m, b)
}
func (m *UserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReq.Marshal(b, m, deterministic)
}
func (m *UserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReq.Merge(m, src)
}
func (m *UserReq) XXX_Size() int {
	return xxx_messageInfo_UserReq.Size(m)
}
func (m *UserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserReq proto.InternalMessageInfo

func (m *UserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 定义服务端响应的数据格式
type UserResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Title                []string `protobuf:"bytes,4,rep,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserResponse) GetTitle() []string {
	if m != nil {
		return m.Title
	}
	return nil
}

type SetUserReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserReq) Reset()         { *m = SetUserReq{} }
func (m *SetUserReq) String() string { return proto.CompactTextString(m) }
func (*SetUserReq) ProtoMessage()    {}
func (*SetUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *SetUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserReq.Unmarshal(m, b)
}
func (m *SetUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserReq.Marshal(b, m, deterministic)
}
func (m *SetUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserReq.Merge(m, src)
}
func (m *SetUserReq) XXX_Size() int {
	return xxx_messageInfo_SetUserReq.Size(m)
}
func (m *SetUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserReq proto.InternalMessageInfo

func (m *SetUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetUserReq) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type SetUserResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserResponse) Reset()         { *m = SetUserResponse{} }
func (m *SetUserResponse) String() string { return proto.CompactTextString(m) }
func (*SetUserResponse) ProtoMessage()    {}
func (*SetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *SetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserResponse.Unmarshal(m, b)
}
func (m *SetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserResponse.Marshal(b, m, deterministic)
}
func (m *SetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserResponse.Merge(m, src)
}
func (m *SetUserResponse) XXX_Size() int {
	return xxx_messageInfo_SetUserResponse.Size(m)
}
func (m *SetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserResponse proto.InternalMessageInfo

func (m *SetUserResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SetUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*UserReq)(nil), "App.Grpc.User.UserReq")
	proto.RegisterType((*UserResponse)(nil), "App.Grpc.User.UserResponse")
	proto.RegisterType((*SetUserReq)(nil), "App.Grpc.User.SetUserReq")
	proto.RegisterType((*SetUserResponse)(nil), "App.Grpc.User.SetUserResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0x54, 0x9c, 0x94, 0x28, 0xcb, 0xa3, 0x68, 0x85, 0x50, 0x28, 0x02, 0x55, 0x39, 0xf5, 0xe4,
	0x43, 0xf9, 0x00, 0x44, 0x85, 0x54, 0x71, 0x75, 0xc5, 0xa5, 0xb7, 0x36, 0x59, 0x50, 0x24, 0x1a,
	0x1b, 0xdb, 0xf0, 0x33, 0xfc, 0x2c, 0xf2, 0x23, 0xa9, 0x40, 0xd0, 0x93, 0x67, 0x77, 0x67, 0xc6,
	0x63, 0x2f, 0xc0, 0x87, 0x21, 0xcd, 0x95, 0x96, 0x56, 0xe2, 0xe9, 0x83, 0x52, 0x7c, 0xa9, 0x55,
	0xcd, 0x9f, 0x0d, 0xe9, 0xea, 0x06, 0x72, 0x77, 0x0a, 0x7a, 0x47, 0x84, 0xac, 0xdb, 0xec, 0xa8,
	0x4c, 0xa6, 0xc9, 0xac, 0x10, 0x1e, 0x57, 0x6b, 0x38, 0x09, 0x63, 0xa3, 0x64, 0x67, 0x08, 0xcf,
	0x80, 0xb5, 0x8d, 0x67, 0x8c, 0x04, 0x6b, 0x9b, 0x41, 0xc3, 0xf6, 0x1a, 0x3c, 0x87, 0x74, 0xf3,
	0x4a, 0x65, 0xea, 0x49, 0x0e, 0xe2, 0x05, 0x8c, 0x6c, 0x6b, 0xdf, 0xa8, 0xcc, 0xa6, 0xe9, 0xac,
	0x10, 0xa1, 0xa8, 0xe6, 0x00, 0x2b, 0xb2, 0x07, 0x6e, 0xef, 0x9d, 0xd8, 0xe0, 0x54, 0xdd, 0xc3,
	0x78, 0xd0, 0xc4, 0x48, 0x08, 0x59, 0x2d, 0x1b, 0x8a, 0xa1, 0x3c, 0xc6, 0x12, 0xf2, 0x1d, 0x19,
	0xd3, 0x8b, 0x0b, 0xd1, 0x97, 0xf3, 0xaf, 0x04, 0xc6, 0x4e, 0xfe, 0xd4, 0xbd, 0xc8, 0x15, 0xe9,
	0xcf, 0xb6, 0x26, 0x5c, 0xc0, 0xf1, 0x32, 0x98, 0xba, 0x2e, 0x5e, 0xf2, 0x1f, 0x5f, 0xc4, 0x63,
	0xc2, 0xc9, 0xf5, 0x9f, 0xfd, 0x98, 0xe2, 0x11, 0xf2, 0x18, 0x0c, 0xaf, 0x7e, 0xf1, 0xf6, 0x8f,
	0x9c, 0xdc, 0xfe, 0x37, 0x0a, 0x2e, 0x8b, 0x6c, 0xcd, 0xd4, 0x76, 0x7b, 0xe4, 0x37, 0x75, 0xf7,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0xef, 0x3b, 0x4d, 0x38, 0xb7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserInfoServiceClient is the client API for UserInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserInfoServiceClient interface {
	// rpc 定义服务内的 GetUserInfo 远程调用
	GetUserInfo(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserResponse, error)
	SetUser(ctx context.Context, in *SetUserReq, opts ...grpc.CallOption) (*SetUserResponse, error)
}

type userInfoServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserInfoServiceClient(cc *grpc.ClientConn) UserInfoServiceClient {
	return &userInfoServiceClient{cc}
}

func (c *userInfoServiceClient) GetUserInfo(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/App.Grpc.User.UserInfoService/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInfoServiceClient) SetUser(ctx context.Context, in *SetUserReq, opts ...grpc.CallOption) (*SetUserResponse, error) {
	out := new(SetUserResponse)
	err := c.cc.Invoke(ctx, "/App.Grpc.User.UserInfoService/SetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserInfoServiceServer is the server API for UserInfoService service.
type UserInfoServiceServer interface {
	// rpc 定义服务内的 GetUserInfo 远程调用
	GetUserInfo(context.Context, *UserReq) (*UserResponse, error)
	SetUser(context.Context, *SetUserReq) (*SetUserResponse, error)
}

// UnimplementedUserInfoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserInfoServiceServer struct {
}

func (*UnimplementedUserInfoServiceServer) GetUserInfo(ctx context.Context, req *UserReq) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (*UnimplementedUserInfoServiceServer) SetUser(ctx context.Context, req *SetUserReq) (*SetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUser not implemented")
}

func RegisterUserInfoServiceServer(s *grpc.Server, srv UserInfoServiceServer) {
	s.RegisterService(&_UserInfoService_serviceDesc, srv)
}

func _UserInfoService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInfoServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/App.Grpc.User.UserInfoService/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInfoServiceServer).GetUserInfo(ctx, req.(*UserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInfoService_SetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInfoServiceServer).SetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/App.Grpc.User.UserInfoService/SetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInfoServiceServer).SetUser(ctx, req.(*SetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserInfoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "App.Grpc.User.UserInfoService",
	HandlerType: (*UserInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _UserInfoService_GetUserInfo_Handler,
		},
		{
			MethodName: "SetUser",
			Handler:    _UserInfoService_SetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
