<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace App\GPBMetadata;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac9010a0b68656c6c6f2e70726f746f120e4170702e477270632e48656c" .
            "6c6f22180a0848656c6c6f526571120c0a046e616d65180120012809222e" .
            "0a0d48656c6c6f526573706f6e7365120c0a046e616d6518012001280912" .
            "0f0a076d65737361676518022001280932520a0b496e666f536572766963" .
            "6512430a0853617948656c6c6f12182e4170702e477270632e48656c6c6f" .
            "2e48656c6c6f5265711a1d2e4170702e477270632e48656c6c6f2e48656c" .
            "6c6f526573706f6e736542045a027062620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

